title: Tu primer p치gina con Django
description: Autor: Rodrigo Sebasti치n M치rquez, Mentor de Program치 tu Futuro, Sede CMD.
Basado en el tutorial de Django Girls :
show_downloads: true
google_analytics:
theme: 
